"""Generate the VMD Tcl deck that loads a lineage.

Default strategy: hand VMD the list of segment DCDs and let it concatenate in
memory, one `mol addfile` per segment with `first`/`last`/`step`. Nothing is
written to disk, the load starts immediately, and there is no artifact to
invalidate. `pgd export` is the command that materializes bytes.

Two things VMD does badly that this deck must defend against:

  * An atom-count mismatch is SILENT. Loading a 234,549-atom DCD into a
    24,790-atom molecule prints "ERROR) Incorrect number of atoms" to stderr
    but raises no Tcl error and loads nothing. So every addfile is followed by
    a frame-count assertion.
  * `mol new <parm7>` yields 0 frames, so VMD frame N maps 1:1 to provenance
    row N with no offset.
"""

from __future__ import annotations

from pathlib import Path

# Ultra_RL2 is a Cas-family protein + sgRNA + dsDNA duplex. After stripping
# there is no water and no ions at all, so no solvent rep is needed.
DEFAULT_REPS = """
mol delrep 0 top
mol representation NewCartoon 0.30 12.0 4.1 0
mol color Structure
mol selection {protein}
mol addrep top
mol representation NewRibbons 0.30 12.0 2.6 0
mol color ColorID 1
mol selection {resname A C G U RA RC RG RU A5 A3 U5 U3 G5 G3 C5 C3}
mol addrep top
mol representation NewRibbons 0.30 12.0 2.6 0
mol color ColorID 0
mol selection {resname DA DT DG DC DA5 DA3 DT5 DT3 DG5 DG3 DC5 DC3}
mol addrep top
display projection Orthographic
axes location Off
color Display Background white
"""


def _tcl_str(p) -> str:
    return '"%s"' % str(p).replace("\\", "\\\\").replace('"', '\\"')


def write_tcl(out_path, topology, resolved_slices, natoms_expect,
              nframes_expect, title, reps_file=None, provenance=None,
              goto_frame=0, extra_tcl=None) -> Path:
    """Emit the deck.

    resolved_slices: [(dcd_path, Slice)] in root->tip order.
    provenance: optional [(iter, seg, local_frame, t_ps)] per emitted frame,
                baked into a Tcl array so `prov` works inside VMD.
    """
    out_path = Path(out_path)
    L = []
    a = L.append

    a("# Generated by pgd -- do not edit; regenerate with the same pgd command.")
    a("# %s" % title)
    a("")
    a("set PGD_TOP %s" % _tcl_str(topology))
    a("set PGD_NATOMS %d" % natoms_expect)
    a("set PGD_NFRAMES %d" % nframes_expect)
    a("")
    a("mol new $PGD_TOP type parm7 waitfor all")
    a("if {[molinfo top get numatoms] != $PGD_NATOMS} {")
    a('    error "topology atom count [molinfo top get numatoms] != expected $PGD_NATOMS"')
    a("}")
    a("set PGD_MOL [molinfo top]")
    a("")
    a("# VMD does NOT raise a Tcl error when a DCD's atom count disagrees with")
    a("# the molecule -- it prints to stderr and silently loads nothing. Assert.")
    a("proc pgd_add {f first last step want} {")
    a("    set before [molinfo top get numframes]")
    a("    mol addfile $f type dcd first $first last $last step $step \\")
    a("        waitfor all molid [molinfo top]")
    a("    set got [expr {[molinfo top get numframes] - $before}]")
    a("    if {$got != $want} {")
    a('        error "addfile $f contributed $got frames, expected $want -- check stderr for \'Incorrect number of atoms\'"')
    a("    }")
    a("}")
    a("")

    for path, sl in resolved_slices:
        first, last, step = sl.to_vmd_addfile()
        a("pgd_add %s %d %d %d %d   ;# iter %d seg %d"
          % (_tcl_str(path), first, last, step, sl.n_frames,
             sl.n_iter, sl.seg_id))

    a("")
    a("set PGD_GOT [molinfo top get numframes]")
    a("if {$PGD_GOT != $PGD_NFRAMES} {")
    a('    error "loaded $PGD_GOT frames, expected $PGD_NFRAMES"')
    a("}")
    a('puts "PGD_FRAMES=$PGD_GOT"')
    a('puts "PGD_ATOMS=[molinfo top get numatoms]"')
    a("mol rename $PGD_MOL %s" % _tcl_str(title))
    a("")

    if provenance:
        a("# frame -> (iteration, segment, local frame, original time)")
        a("array set PGD_PROV {")
        for i, (it, seg, lf, t) in enumerate(provenance):
            a("  %d {iter %d seg %d frame %d t %.1fps}" % (i, it, seg, lf, t))
        a("}")
        a("proc prov {{f -1}} {")
        a("    global PGD_PROV")
        a("    if {$f < 0} { set f [molinfo top get frame] }")
        a("    if {[info exists PGD_PROV($f)]} {")
        a('        puts "frame $f -> $PGD_PROV($f)"')
        a("    } else {")
        a('        puts "frame $f -> (no provenance)"')
        a("    }")
        a("}")
        a('puts "pgd: type  prov  to identify the current frame"')
        a("")

    # Colvars goes in BEFORE the representations: a user --reps file is a
    # natural place to call cvs/cvtrace or colour by a collective variable,
    # and it can only do that if the helpers already exist.
    if extra_tcl:
        a(extra_tcl)
        a("")

    if reps_file:
        a("source %s" % _tcl_str(reps_file))
    else:
        a(DEFAULT_REPS.strip())

    a("")
    a("animate goto %d" % goto_frame)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(L) + "\n")
    return out_path


def write_preflight_tcl(out_path, topology, resolved_slices, natoms_expect,
                        nframes_expect) -> Path:
    """A minimal deck for `vmd_2 -dispdev text -eofexit`.

    Same loads and assertions, no representations, quits at the end -- so a
    frame-count mismatch is reported in the shell rather than inside a window
    the user then has to read.
    """
    out_path = Path(out_path)
    L = ["# pgd preflight -- assertions only, no display",
         "mol new %s type parm7 waitfor all" % _tcl_str(topology)]
    for path, sl in resolved_slices:
        first, last, step = sl.to_vmd_addfile()
        L.append("mol addfile %s type dcd first %d last %d step %d "
                 "waitfor all molid top" % (_tcl_str(path), first, last, step))
    L += ['puts "PGD_FRAMES=[molinfo top get numframes]"',
          'puts "PGD_ATOMS=[molinfo top get numatoms]"',
          "quit"]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(L) + "\n")
    return out_path
